=== kupcza/workshop/6-rest2soap/response.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns="http://www.jpower8.com/newDeveloper/soap"
           targetNamespace="http://www.jpower8.com/newDeveloper/soap">
    <xs:element name="PointsOfInterestsRes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="requestID" type="xs:string"/>
                <xs:element name="places">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="item">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="timestamp" type="xs:string"/>
                                        <xs:element name="id" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="street" type="xs:string"/>
                                                    <xs:element name="houseNo" type="xs:string"/>
                                                    <xs:element name="town" type="xs:string"/>
                                                    <xs:element name="postal" type="xs:string"/>
                                                    <xs:element name="country" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="type">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="atm"/>
                                                    <xs:enumeration value="cp"/>
                                                    <xs:enumeration value="office"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="url" type="xs:string"/>
                                        <xs:element name="hours">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="7" name="hour">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="day">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:byte">
                                                                            <xs:pattern value="[1-7]{1}"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="from">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:maxLength value="5"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="to">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:maxLength value="5"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="filter" nillable="false">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="pageLimit" type="xs:int"/>
                            <xs:element name="brand">
                                <xs:simpleType>
                                    <xs:restriction base="xs:byte">
                                        <xs:enumeration value="1"/>
                                        <xs:enumeration value="2"/>
                                        <xs:enumeration value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="brandName" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== kupcza/workshop/5-rest2soap/response1.xml
<?xml version="1.0" encoding="UTF-8"?>
<PointsOfInterestsRes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/Petr/jPower8/new-developer/response.xsd">
    <places>
        <item>
            <id>0</id>
            <name>name0</name>
            <address>
                <street>street0</street>
                <houseNo>houseNo0</houseNo>
                <town>town0</town>
                <postal>postal0</postal>
                <country>country0</country>
            </address>
            <type>atm</type>
            <url>url0</url>
            <hours>
                <hour>
                    <day>4</day>
                    <from>from0</from>
                    <to>to0</to>
                </hour>
                <hour>
                    <day>5</day>
                    <from>from1</from>
                    <to>to1</to>
                </hour>
                <hour>
                    <day>6</day>
                    <from>from2</from>
                    <to>to2</to>
                </hour>
                <hour>
                    <day>7</day>
                    <from>from3</from>
                    <to>to3</to>
                </hour>
            </hours>
        </item>
        <item>
            <id>0</id>
            <name>name1</name>
            <address>
                <street>street1</street>
                <houseNo>houseNo1</houseNo>
                <town>town1</town>
                <postal>postal1</postal>
                <country>country1</country>
            </address>
            <type>atm</type>
            <url>url1</url>
            <hours>
                <hour>
                    <day>1</day>
                    <from>from4</from>
                    <to>to4</to>
                </hour>
                <hour>
                    <day>2</day>
                    <from>from5</from>
                    <to>to5</to>
                </hour>
                <hour>
                    <day>3</day>
                    <from>from6</from>
                    <to>to6</to>
                </hour>
                <hour>
                    <day>4</day>
                    <from>from7</from>
                    <to>to7</to>
                </hour>
            </hours>
        </item>
        <item>
            <id>0</id>
            <name>name2</name>
            <address>
                <street>street2</street>
                <houseNo>houseNo2</houseNo>
                <town>town2</town>
                <postal>postal2</postal>
                <country>country2</country>
            </address>
            <type>atm</type>
            <url>url2</url>
            <hours>
                <hour>
                    <day>2</day>
                    <from>from8</from>
                    <to>to8</to>
                </hour>
                <hour>
                    <day>3</day>
                    <from>from9</from>
                    <to>to9</to>
                </hour>
                <hour>
                    <day>4</day>
                    <from>from1</from>
                    <to>to10</to>
                </hour>
                <hour>
                    <day>5</day>
                    <from>from1</from>
                    <to>to11</to>
                </hour>
            </hours>
        </item>
        <item>
            <id>0</id>
            <name>name3</name>
            <address>
                <street>street3</street>
                <houseNo>houseNo3</houseNo>
                <town>town3</town>
                <postal>postal3</postal>
                <country>country3</country>
            </address>
            <type>atm</type>
            <url>url3</url>
            <hours>
                <hour>
                    <day>1</day>
                    <from>from1</from>
                    <to>to12</to>
                </hour>
                <hour>
                    <day>2</day>
                    <from>from1</from>
                    <to>to13</to>
                </hour>
                <hour>
                    <day>3</day>
                    <from>from1</from>
                    <to>to14</to>
                </hour>
                <hour>
                    <day>7</day>
                    <from>from2</from>
                    <to>to15</to>
                </hour>
            </hours>
        </item>
    </places>
    <filter>
        <type>type4</type>
        <pageLimit>0</pageLimit>
        <brand>1</brand>
    </filter>
</PointsOfInterestsRes>
